import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/** 复制 pdf.js worker 资源到插件目录（构建期执行）。 */
async function copyPdfWorker() {
	const src = path.join(__dirname, "node_modules", "pdfjs-dist", "build", "pdf.worker.min.mjs");
	const dest = path.join(__dirname, "pdf.worker.min.mjs");
	fs.copyFileSync(src, dest);
	console.log(`[esbuild] copied pdf.worker.min.mjs (${(fs.statSync(dest).size / 1024).toFixed(0)} KB)`);
}

const context = await esbuild.context({
	banner: { js: banner, css: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await copyPdfWorker();
	process.exit(0);
} else {
	await context.watch();
	// watch 模式下也复制一次
	await copyPdfWorker();
}
